rails/10 - egresso/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  root 'home#index'

  resources :students
  resources :courses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/10 - egresso/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails/10 - egresso/app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :student

  validates :tipo, presence: true, inclusion: {in: %w(email telefone facebook instagram linkedin twitter) }
  validates :valor, presence: true
end

rails/10 - egresso/app/models/coordinator.rb
class Coordinator < ApplicationRecord
	belongs_to :course

	validates :nome, presence: true
	validates :matricula, presence: true
	validates :senha, presence: true
end

rails/10 - egresso/app/models/course.rb
class Course < ApplicationRecord
	has_one :coordinator
	has_many :students

	validates :nome, presence: true
	validates :sigla, presence: true
	validates :site, presence: true

	accepts_nested_attributes_for :coordinator
end

rails/10 - egresso/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course

  has_many :contacts

  validates :nome, presence: true
  validates :matricula, presence: true
  validates :senha, presence: true
  validates :ano, presence: true
  validates :semestre, presence: true

  accepts_nested_attributes_for :contacts, reject_if: :all_blank, allow_destroy: :true
end

rails/10 - egresso/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

rails/10 - egresso/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails/10 - egresso/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # http_basic_authenticate_with name:"valeria", password:"1234"

  before_action :authenticate_user!
  

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all.page(params[:page]).per(10)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
    @course.build_coordinator
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params_new)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params_edit)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.coordinator.destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params_new
      params.require(:course).permit(:nome, :sigla, :site,
              coordinator_attributes: [:nome, :matricula, :senha])
    end

    def course_params_edit
      params.require(:course).permit(:nome, :sigla, :site,
              coordinator_attributes: [:nome, :matricula, :senha, :id])
    end
end

rails/10 - egresso/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

rails/10 - egresso/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.page(params[:page]).per(10)
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
    @cursos = Course.all
  end

  # GET /students/1/edit
  def edit
    @cursos = Course.all
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(
            :nome, :matricula, 
            :ano, :semestre, :senha, :course_id,
            contacts_attributes:[:id, :tipo, :valor, :_destroy])
    end
end

rails/10 - egresso/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/10 - egresso/app/helpers/courses_helper.rb
module CoursesHelper
end

rails/10 - egresso/app/helpers/home_helper.rb
module HomeHelper
end

rails/10 - egresso/app/helpers/students_helper.rb
module StudentsHelper
end

rails/10 - egresso/app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :course_nome %>
  </div>

  <div class="field">
    <%= form.label :sigla %>
    <%= form.text_field :sigla, id: :course_sigla %>
  </div>

  <div class="field">
    <%= form.label :site %>
    <%= form.text_field :site, id: :course_site %>
  </div>

  <%= form.fields_for :coordinator do |coordinator_fields| %>

    <div class="field">
      <%= coordinator_fields.label :nome %>
      <%= coordinator_fields.text_field :nome, id: :coordinator_nome %>
    </div>

    <div class="field">
      <%= coordinator_fields.label :matricula %>
      <%= coordinator_fields.text_field :matricula, id: :coordinator_matricula %>
    </div>

    <div class="field">
      <%= coordinator_fields.label :senha %>
      <%= coordinator_fields.text_field :senha, id: :coordinator_senha %>
    </div>

  <% end %>

  <div class="actions">
    <%= form.submit 'salvar', :class => 'btn btn-success' %>
  </div>
<% end %>

rails/10 - egresso/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

rails/10 - egresso/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sigla</th>
      <th>Site</th>
      <th>Coordenador</th>
      <th>Matricula</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.nome %></td>
        <td><%= course.sigla %></td>
        <td><%= course.site %></td>
        <td><%= course.coordinator.nome %></td>
        <td><%= course.coordinator.matricula %></td>
        <td><%= course.coordinator.senha %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate(@courses, theme: "google") %>

<br>

<%= link_to 'New Course', new_course_path, :class => "btn btn-success" %>

rails/10 - egresso/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<br>

<%= link_to 'Back', courses_path, :class => "btn btn-warning" %>

rails/10 - egresso/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @course.nome %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @course.sigla %>
</p>

<p>
  <strong>Site:</strong>
  <%= @course.site %>
</p>

<p>
  <strong>Coordenador:</strong>
  <%= @course.coordinator.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @course.coordinator.matricula %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @course.coordinator.senha %>
</p>

<h2>Estudantes</h2>

<table class="table">
   <thead>
     <tr>
       <td>Nome</td>
       <td>Matrícula</td>
     </tr>
   </thead>
   <tbody>
      <% for estudante in @course.students %>
          <tr>
            <td><%= estudante.nome %></td>
            <td><%= estudante.matricula %></td>
          </tr>
      <% end %>     
   </tbody>
</table>

<br>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

rails/10 - egresso/app/views/home/index.html.erb
<div class="jumbotron" align="center">
  <h1 class="display-4">Egresso</h1>
  <p class="lead">Instituto Federal de Educação, Ciência e Tecnologia da Paraíba - IFPB.</p>
  <hr class="my-4">
  <p>Campus João Pessoa</p>

  <h1> <%= t "idioma" %> </h1>
  <h1> <%= t "fofo" %> </h1>
  <h1> <%= l Date.today %> </h1>
</div>

rails/10 - egresso/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <a class="navbar-brand" href="<%= root_path %>">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<%= courses_path %>">Cursos <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="<%= students_path %>">Estudantes</a>
    </div>
  </div>
</nav>

<% if user_signed_in? %>
  <%= current_user.email %> - <%= link_to "Sair", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_user_session_path %>
<% end %>

<br>
<%= user_session %>
<br>

rails/10 - egresso/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Egresso</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render partial: "layouts/menu" %>
    <%= yield %>
  </body>
</html>

rails/10 - egresso/app/views/students/_contact_fields.html.erb
<div class = "nested-fields">
	<div class = "field">

		<%
			if (@student.contacts.count == 0)
				opcao = "email"
			else
				opcao = @student.contacts[f.index.to_i].tipo
			end
		%>

		<%= f.label :tipo %>
		<%= f.select :tipo, options_for_select([
								["e-mail", "email"],
								["Telefone", "telefone"]
							], opcao) %>

		<%= f.label :valor %>
		<%= f.text_field :valor %>

		<%= link_to_remove_association('[Remover]', f) %>
	</div>
</div>

rails/10 - egresso/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :student_nome %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.text_field :matricula, id: :student_matricula %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano, id: :student_ano %>
  </div>

  <div class="field">
    <%= form.label :semestre %>
    <%= form.number_field :semestre, id: :student_semestre %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :student_senha %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= collection_select(:student, :course_id, Course.all, :id, :nome) %>
  </div>

  <div id = "contacts">
    <%= form.fields_for :contacts do |contacts_fields| %>
      <%= render partial: "contact_fields", locals: {f: contacts_fields} %>
    <% end %>

    <%= link_to_add_association('[ Adicionar Contato ]', form, :contacts) %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', :class => 'btn btn-success' %>
  </div>
<% end %>

rails/10 - egresso/app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

rails/10 - egresso/app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Matricula</th>
      <th>Ano</th>
      <th>Semestre</th>
      <th>Senha</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.nome %></td>
        <td><%= student.matricula %></td>
        <td><%= student.ano %></td>
        <td><%= student.semestre %></td>
        <td><%= student.senha %></td>
        <td><%= student.course.sigla %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= paginate(@students, theme: "bootstrap4") %>

<br>

<%= link_to 'New Student', new_student_path, :class => 'btn btn-success' %>

rails/10 - egresso/app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<br>

<%= link_to 'Back', students_path, :class => 'btn btn-warning' %>

rails/10 - egresso/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @student.nome %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @student.matricula %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @student.ano %>
</p>

<p>
  <strong>Semestre:</strong>
  <%= @student.semestre %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @student.senha %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course.nome %>
</p>


<h2>Contatos</h2>

<table class="table">
   <thead>
     <tr>
       <td>Tipo</td>
       <td>Valor</td>
     </tr>
   </thead>
   <tbody>
      <% for contato in @student.contacts %>
          <tr>
            <td><%= contato.tipo %></td>
            <td><%= contato.valor %></td>
          </tr>
      <% end %>     
   </tbody>
</table>

<br>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

rails/10 - egresso/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>