rails/04 - contatos/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get 'pessoas' => 'people#index'

  resources :emails#, only: [:index, :show]
  resources :people#, except: [:index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/04 - contatos/app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
end

rails/04 - contatos/app/models/person.rb
class Person < ApplicationRecord
end

rails/04 - contatos/app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
    @pessoas = Person.all
  end

  # GET /emails/1/edit
  def edit
    @pessoas = Person.all
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:endereco, :person_id)
    end
end

rails/04 - contatos/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

rails/04 - contatos/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:nome, :abreviacao, :nascimento)
    end
end

rails/04 - contatos/app/helpers/emails_helper.rb
module EmailsHelper
end

rails/04 - contatos/app/helpers/people_helper.rb
module PeopleHelper
end

rails/04 - contatos/app/views/home/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Contatinhos</h1>
  <p class="lead">Contatinhos do IFPB - Campus JP</p>
  <hr class="my-4">
  <p>CST em Sistemas para Internet</p>
  <p>RAD - 2018.1</p>
</div>

rails/04 - contatos/app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#"><%= p1 %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= people_path %>">Pessoas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= emails_path %>">e-mails</a>
      </li>
    </ul>
  </div>
</nav>

rails/04 - contatos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contatos</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% nome_app = "Contatos" %>

    <%= render partial: "/layouts/menu", locals: { p1: nome_app } %>	
    <%= yield %>
  </body>
</html>

rails/04 - contatos/app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :person_nome %>
  </div>

  <div class="field">
    <%= form.label :abreviacao %>
    <%= form.text_field :abreviacao, id: :person_abreviacao %>
  </div>

  <div class="field">
    <%= form.label :nascimento %>
    <%= form.datetime_select :nascimento, id: :person_nascimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

rails/04 - contatos/app/views/people/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Nome</th>
      <th>Abreviacao</th>
      <th>Nascimento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= person.nome %></td>
        <td><%= person.abreviacao %></td>
        <td><%= person.nascimento %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

rails/04 - contatos/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

rails/04 - contatos/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<%= render partial: "table" %>

<br>

<%= link_to 'New Person', new_person_path %>

rails/04 - contatos/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

rails/04 - contatos/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @person.nome %>
</p>

<p>
  <strong>Abreviacao:</strong>
  <%= @person.abreviacao %>
</p>

<p>
  <strong>Nascimento:</strong>
  <%= @person.nascimento %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>